;
; File generated by co65 v 2.17 using model 'none'
;
.fopt		compiler,"co65 v 2.17"
.case		on
.debuginfo	off

_boot_microdisc = CODE+0
.export	_boot_microdisc
EndOfMemory = +20660
.export	EndOfMemory

;
; CODE SEGMENT
;
.segment	"CODE"
CODE:
	.byte	$78
	.byte	$A9
	.byte	$00
	.byte	$8D
	.byte	$21
	.byte	$03
	.byte	$A9
	.byte	$60
	.byte	$85
	.byte	$00
	.byte	$20
	.byte	$00
	.byte	$00
	.byte	$BA
	.byte	$CA
	.byte	$18
	.byte	$BD
	.byte	$00
	.byte	$01
	.byte	$69
	.byte	$22
	.byte	$85
	.byte	$00
	.byte	$BD
	.byte	$01
	.byte	$01
	.byte	$69
	.byte	$00
	.byte	$85
	.byte	$01
	.byte	$A0
	.byte	$00
	.byte	$B1
	.byte	$00
	.byte	$99
	.byte	$00
	.byte	$50
	.byte	$C8
	.byte	$CC
	.byte	$B3
	.byte	$00
	.byte	$D0
	.byte	$F5
	.byte	$4C
	.byte	$00
	.byte	$50
	.byte	$A0
	.byte	$27
	.byte	$A9
	.byte	$00
	.byte	$AA
	.byte	$9D
	.byte	$00
	.byte	$99
	.byte	$E8
	.byte	$D0
	.byte	$FA
	.byte	$EE
	.byte	$07
	.byte	$50
	.byte	$88
	.byte	$D0
	.byte	$F3
	.byte	$A9
	.byte	$1E
	.byte	$8D
	.byte	$DF
	.byte	$BF
	.byte	$20
	.byte	$9B
	.byte	$50
	.byte	$A0
	.byte	$04
	.byte	$8C
	.byte	$B2
	.byte	$50
	.byte	$EA
	.byte	$EA
	.byte	$EA
	.byte	$A2
	.byte	$00
	.byte	$EA
	.byte	$EA
	.byte	$EA
	.byte	$EC
	.byte	$11
	.byte	$03
	.byte	$F0
	.byte	$1D
	.byte	$8E
	.byte	$13
	.byte	$03
	.byte	$EA
	.byte	$EA
	.byte	$EA
	.byte	$AD
	.byte	$18
	.byte	$03
	.byte	$30
	.byte	$F8
	.byte	$A9
	.byte	$1F
	.byte	$EA
	.byte	$8D
	.byte	$10
	.byte	$03
	.byte	$A0
	.byte	$04
	.byte	$88
	.byte	$D0
	.byte	$FD
	.byte	$AD
	.byte	$10
	.byte	$03
	.byte	$4A
	.byte	$B0
	.byte	$FA
	.byte	$0A
	.byte	$A9
	.byte	$02
	.byte	$EA
	.byte	$8D
	.byte	$12
	.byte	$03
	.byte	$A9
	.byte	$84
	.byte	$8D
	.byte	$14
	.byte	$03
	.byte	$A9
	.byte	$80
	.byte	$8D
	.byte	$10
	.byte	$03
	.byte	$A0
	.byte	$1E
	.byte	$EA
	.byte	$EA
	.byte	$88
	.byte	$D0
	.byte	$FB
	.byte	$A0
	.byte	$00
	.byte	$AD
	.byte	$18
	.byte	$03
	.byte	$30
	.byte	$FB
	.byte	$AD
	.byte	$13
	.byte	$03
	.byte	$99
	.byte	$00
	.byte	$60
	.byte	$C8
	.byte	$D0
	.byte	$F2
	.byte	$EA
	.byte	$EA
	.byte	$AD
	.byte	$10
	.byte	$03
	.byte	$29
	.byte	$1C
	.byte	$F0
	.byte	$05
	.byte	$CE
	.byte	$B2
	.byte	$50
	.byte	$D0
	.byte	$A1
	.byte	$EE
	.byte	$49
	.byte	$50
	.byte	$EE
	.byte	$6B
	.byte	$50
	.byte	$CE
	.byte	$B1
	.byte	$50
	.byte	$D0
	.byte	$96
	.byte	$78
	.byte	$A9
	.byte	$81
	.byte	$8D
	.byte	$14
	.byte	$03
	.byte	$A2
	.byte	$00
	.byte	$A9
	.byte	$6F
	.byte	$8D
	.byte	$2E
	.byte	$03
	.byte	$AD
	.byte	$08
	.byte	$03
	.byte	$4C
	.byte	$18
	.byte	$60
	.byte	$A9
	.byte	$0C
	.byte	$8D
	.byte	$10
	.byte	$03
	.byte	$20
	.byte	$A8
	.byte	$50
	.byte	$29
	.byte	$10
	.byte	$D0
	.byte	$F4
	.byte	$60
	.byte	$AD
	.byte	$14
	.byte	$03
	.byte	$30
	.byte	$FB
	.byte	$AD
	.byte	$10
	.byte	$03
	.byte	$60
	.byte	$01
	.byte	$00
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	0

;
; ZEROPAGE SEGMENT
;
.segment	"ZEROPAGE": zeropage
ZEROPAGE:
	.res	0

.end
